### ISSUE TITLE
add note to update git - gist-snap doesn't work for old git version 1.8.2.3

### ISSUE THREAD

**Issue by micahstubbs** [1wheel/gistsnap#1]
would be nice to add a note to the `README.md` telling users who have a clean working state but still see an error message that they should update git in order to generate the exact git response text that `gist-snap` checks for.

after I updated to the latest git `2.6.2` gist-snap worked just fine 😄

**Comment by 1wheel** [comment]
Added a check/logging for the git version in 7d0bfd0348b3039625d45ed05652dcb178596cba
