### ISSUE TITLE
add verbose terminal logging

### ISSUE THREAD

**Issue by micahstubbs** [1wheel/gistsnap#3]
would be nice to have a verbose mode that logs out a message to the terminal everytime something happens, like:

``` shell
$ gist-snap
#...
$ rendered index.html 
$ captured image
$ saved image as preview.png
$ resized image
$ saved image as thumbnail.png
# ...
```

**Comment by 1wheel** [comment]
I removed the auto git committing and added `Nightmare({show: true})` so you can see what's getting screen shotted. Probably don't need more logging?

**Comment by micahstubbs** [comment]
👍
