### ISSUE TITLE
Headless?

### ISSUE THREAD

**Issue by curran** [1wheel/gistsnap#6]
I wonder what it would take, or if it's even possible, to make this tool work in a headless environment like an AWS server.

I've tried it, and the program hangs indefinitely without any output.

Related article [Running nightmare on Amazon Linux](https://gist.github.com/dimkir/f4afde77366ff041b66d2252b45a13db).

Perhaps the `{show:true}` could be configurable with command line arguments.

Any thoughts?

**Comment by 1wheel** [comment]
Let me know if that works! 

Otherwise, I've had luck with https://github.com/GoogleChrome/puppeteer
